language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mdycz/docker-react-ci .

script:
  - docker run -e CI=true mdycz/docker-react-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-ci"
  env: "DockerReactCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-780625217371"
  bucket_path: "docker-react-ci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY